//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPracticBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int id_sklad { get; set; }
        public string name { get; set; }
        public int id_lavash { get; set; }
        public int id_luck { get; set; }
        public int id_myaso { get; set; }
        public int id_ogurec { get; set; }
        public int id_pomidori { get; set; }
        public int id_sosiska { get; set; }
    
        public virtual lavash lavash { get; set; }
        public virtual Luck Luck { get; set; }
        public virtual myasko myasko { get; set; }
        public virtual ogurci ogurci { get; set; }
        public virtual pomidori pomidori { get; set; }
        public virtual sosiska sosiska { get; set; }
    }
}
