//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPracticBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class uslugi
    {
        public int id_usluga { get; set; }
        public string name { get; set; }
        public int id_price { get; set; }
        public int id_time { get; set; }
        public int id_sprice { get; set; }
    
        public virtual price price { get; set; }
        public virtual sprice sprice { get; set; }
        public virtual time time { get; set; }
    }
}
