//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPracticBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        public int id_zakaza { get; set; }
        public string name { get; set; }
        public Nullable<int> id_usluga { get; set; }
        public Nullable<int> id_price { get; set; }
        public Nullable<int> id_time { get; set; }
        public Nullable<int> id_image { get; set; }
    
        public virtual price price { get; set; }
        public virtual time time { get; set; }
        public virtual uslugi uslugi { get; set; }
        public virtual images images { get; set; }
    }
}
